version:  "3.9"
services:
  cockroach:
    container_name: cockroach
    hostname: cockroach
    networks:
      - backend
    image: cockroachdb/cockroach
    command: start-single-node --insecure 
    restart: always
    volumes:
      - ./cockroach-data:/cockroach/cockroach-data  
    ports:
      - "26257:26257"
      - "8080:8080"
  redis:
    container_name: redis
    hostname: redis
    networks:
      - backend
    image: redis
    ports:
      - "6379:6379"
  filestorage:
    container_name: filestorage
    hostname: filestorage
    image: filestorage
    networks:
      - backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=cockroach
      - DB_NAME=defaultdb
    restart: always

networks:
  backend:
    driver: bridge
